services:
    skydiablo.swiftmailer-extension.css2inline-styles:
        class: SkyDiablo\SwiftmailerExtensionBundle\Service\CssToInlineStylesService

    skydiablo.swiftmailer-extension.plugin.css2inline:
        class: SkyDiablo\SwiftmailerExtensionBundle\Plugin\CSS2Inline\CSS2InlinePlugin
        arguments:
            - '@skydiablo.swiftmailer-extension.css2inline-styles'
        tags:
            swiftmailer_plugin: # register as swiftmailer plugin
                name: swiftmailer.default.plugin

    skydiablo.swiftmailer-extension.plugin.embedded-media:
        class: SkyDiablo\SwiftmailerExtensionBundle\Plugin\EmbeddedMedia\EmbeddedMediaPlugin
        arguments:
            - '%skydiablo.swiftmailer-extension.plugin.embedded-media.embed-attribute-name%'
            - '%skydiablo.swiftmailer-extension.plugin.embedded-media.default%'
        tags:
            swiftmailer_plugin: # register as swiftmailer plugin
                name: swiftmailer.default.plugin

    skydiablo.swiftmailer-extension.abstract-default-mailer:
        class: SkyDiablo\SwiftmailerExtensionBundle\Service\DefaultMailerService
        calls:
            - [setMailer, ['@mailer']]
            - [setTwig, ['@twig']]
            - [setTranslator, ['@translator']]
            - [setValidator, ['@validator']]
            - [setFileLocator, ['@file_locator']]
            - [setSenderEmailAddress, ['%skydiablo.swiftmailer-extension.email_sender_address%']]
            - [setSenderEmailName, ['%skydiablo.swiftmailer-extension.email_sender_name%']]
        abstract: true

    sky_diablo_swiftmailer_extension.handler_aws.email_return_status_handler:
        class: SkyDiablo\SwiftmailerExtensionBundle\Handler\aws\EmailReturnStatusHandler
        arguments:
            - '@aws.sqs'
            - '%skydiablo.swiftmailer-extension.handler.email_return_status.aws_ses.queue_url%'
            - '%skydiablo.swiftmailer-extension.handler.email_return_status.aws_ses.long_polling_timeout%'
            - '@event_dispatcher'
            - '@logger'